####QSGMII sch page10 bank115
set_property PACKAGE_PIN R3 [get_ports GE_PHY_C_QSGMII0_OUT_N]
set_property PACKAGE_PIN R4 [get_ports GE_PHY_C_QSGMII0_OUT_P]
set_property PACKAGE_PIN P1 [get_ports GE_PHY_C_QSGMII0_IN_N]
set_property PACKAGE_PIN P2 [get_ports GE_PHY_C_QSGMII0_IN_P]
set_property PACKAGE_PIN N3 [get_ports GE_PHY_C_QSGMII1_OUT_N]
set_property PACKAGE_PIN N4 [get_ports GE_PHY_C_QSGMII1_OUT_P]
set_property PACKAGE_PIN M1 [get_ports GE_PHY_C_QSGMII1_IN_N]
set_property PACKAGE_PIN M2 [get_ports GE_PHY_C_QSGMII1_IN_P]
set_property PACKAGE_PIN L3 [get_ports GE_PHY_B_QSGMII0_OUT_N]
set_property PACKAGE_PIN L4 [get_ports GE_PHY_B_QSGMII0_OUT_P]
set_property PACKAGE_PIN K1 [get_ports GE_PHY_B_QSGMII0_IN_N]
set_property PACKAGE_PIN K2 [get_ports GE_PHY_B_QSGMII0_IN_P]
set_property PACKAGE_PIN J3 [get_ports GE_PHY_B_QSGMII1_OUT_N]
set_property PACKAGE_PIN J4 [get_ports GE_PHY_B_QSGMII1_OUT_P]
set_property PACKAGE_PIN H1 [get_ports GE_PHY_B_QSGMII1_IN_N]
set_property PACKAGE_PIN H2 [get_ports GE_PHY_B_QSGMII1_IN_P]
set_property PACKAGE_PIN H6 [get_ports FPGA_GTX_P0_CLK_P]
set_property PACKAGE_PIN H5 [get_ports FPGA_GTX_P0_CLK_N]

####QSGMII sch page10 bank116
set_property PACKAGE_PIN E3 [get_ports GE_PHY_A_QSGMII1_OUT_N]
set_property PACKAGE_PIN E4 [get_ports GE_PHY_A_QSGMII1_OUT_P]
set_property PACKAGE_PIN D1 [get_ports GE_PHY_A_QSGMII1_IN_N]
set_property PACKAGE_PIN D2 [get_ports GE_PHY_A_QSGMII1_IN_P]
set_property PACKAGE_PIN G3 [get_ports GE_PHY_A_QSGMII0_OUT_N]
set_property PACKAGE_PIN G4 [get_ports GE_PHY_A_QSGMII0_OUT_P]
set_property PACKAGE_PIN F1 [get_ports GE_PHY_A_QSGMII0_IN_N]
set_property PACKAGE_PIN F2 [get_ports GE_PHY_A_QSGMII0_IN_P]

#sch page11 bank12
set_property PACKAGE_PIN AD24 [get_ports CPU_ESPI2_RDY]
set_property PACKAGE_PIN AA24 [get_ports CPU_ESPI1_MISO]
set_property PACKAGE_PIN Y23 [get_ports CPU_ENET2_TX_CLK]

#sch page11 bank13
set_property PACKAGE_PIN P18 [get_ports SW_SEL_P00]
set_property PACKAGE_PIN R18 [get_ports SW_SEL_P01]
set_property PACKAGE_PIN T17 [get_ports SW_SEL_P02]
set_property PACKAGE_PIN U17 [get_ports SW_SEL_P03]
set_property PACKAGE_PIN M19 [get_ports SW_SEL_P04]
set_property PACKAGE_PIN N18 [get_ports SW_SEL_P05]
set_property PACKAGE_PIN R17 [get_ports SW_SEL_P06]
set_property PACKAGE_PIN R16 [get_ports SW_SEL_P07]
set_property PACKAGE_PIN N17 [get_ports SW_SEL_P08]
set_property PACKAGE_PIN P16 [get_ports SW_SEL_P09]
set_property PACKAGE_PIN T19 [get_ports SW_SEL_P10]
set_property PACKAGE_PIN T18 [get_ports SW_SEL_P11]
set_property PACKAGE_PIN U20 [get_ports SW_SEL_P12]
set_property PACKAGE_PIN U19 [get_ports SW_SEL_P13]
set_property PACKAGE_PIN T23 [get_ports SW_SEL_P14]
set_property PACKAGE_PIN T22 [get_ports SW_SEL_P15]
set_property PACKAGE_PIN R20 [get_ports SW_SEL_P16]
set_property PACKAGE_PIN T20 [get_ports SW_SEL_P17]
set_property PACKAGE_PIN T25 [get_ports SW_SEL_P18]
set_property PACKAGE_PIN T24 [get_ports SW_SEL_P19]
set_property PACKAGE_PIN R23 [get_ports SW_SEL_P20]
set_property PACKAGE_PIN R22 [get_ports SW_SEL_P21]
set_property PACKAGE_PIN P21 [get_ports SW_SEL_P22]
set_property PACKAGE_PIN R21 [get_ports SW_SEL_P23]
set_property PACKAGE_PIN N23 [get_ports GE_PHY_A_MDC]
set_property PACKAGE_PIN M21 [get_ports GE_PHY_B_MDC]
set_property PACKAGE_PIN L24 [get_ports GE_PHY_C_MDC]
set_property PACKAGE_PIN U21 [get_ports FE_PHY_MDC]

#sch page11 bank15
set_property PACKAGE_PIN K18 [get_ports CPU_ENET2_MDC]
set_property PACKAGE_PIN L20 [get_ports CPU_ENET1_LED_LNKACT]
set_property PACKAGE_PIN L19 [get_ports CPU_ENET1_LED_SPEED]
set_property PACKAGE_PIN J19 [get_ports FPGA_SYS_ETH_LED0]
set_property PACKAGE_PIN J18 [get_ports FPGA_SYS_ETH_LED1]
set_property PACKAGE_PIN F15 [get_ports LED3]
set_property PACKAGE_PIN G15 [get_ports LED4]
set_property PACKAGE_PIN G16 [get_ports LED5]
set_property PACKAGE_PIN H16 [get_ports LED6]
set_property PACKAGE_PIN C18 [get_ports SYS_LED]

#sch page11 bank16
set_property PACKAGE_PIN A12 [get_ports FPGA_GE_LED_P16]
set_property PACKAGE_PIN A13 [get_ports FPGA_GE_LED_P15]
set_property PACKAGE_PIN A15 [get_ports FPGA_GE_LED_P06]
set_property PACKAGE_PIN B15 [get_ports FPGA_GE_LED_P07]
set_property PACKAGE_PIN A10 [get_ports FPGA_GE_LED_P19]
set_property PACKAGE_PIN B10 [get_ports FPGA_GE_LED_P18]
set_property PACKAGE_PIN A14 [get_ports FPGA_GE_LED_P13]
set_property PACKAGE_PIN B14 [get_ports FPGA_GE_LED_P14]
set_property PACKAGE_PIN B11 [get_ports FPGA_GE_LED_P08]
set_property PACKAGE_PIN B12 [get_ports FPGA_GE_LED_P17]
set_property PACKAGE_PIN C13 [get_ports GE_PHY_B_LED_P2]
set_property PACKAGE_PIN C14 [get_ports GE_PHY_B_LED_P5]
set_property PACKAGE_PIN E12 [get_ports FPGA_GE_LED_P03]

set_property PACKAGE_PIN E13 [get_ports GE_PHY_B_LED_P4]
set_property PACKAGE_PIN D13 [get_ports GE_PHY_B_LED_P6]
set_property PACKAGE_PIN D14 [get_ports GE_PHY_B_LED_P7]
set_property PACKAGE_PIN F12 [get_ports GE_PHY_B_LED_P3]
set_property PACKAGE_PIN G12 [get_ports FPGA_GE_LED_P01]
set_property PACKAGE_PIN F13 [get_ports FPGA_GE_LED_P02]
set_property PACKAGE_PIN F14 [get_ports GE_PHY_A_LED_P2]
set_property PACKAGE_PIN D11 [get_ports FPGA_GE_LED_P09]
set_property PACKAGE_PIN E11 [get_ports FPGA_GE_LED_P05]
set_property PACKAGE_PIN C11 [get_ports FPGA_GE_LED_P11]

set_property PACKAGE_PIN C12 [get_ports FPGA_GE_LED_P04]
set_property PACKAGE_PIN D10 [get_ports FPGA_GE_LED_P12]
set_property PACKAGE_PIN E10 [get_ports FPGA_GE_LED_P23]
set_property PACKAGE_PIN F10 [get_ports FPGA_GE_LED_P22]
set_property PACKAGE_PIN G11 [get_ports GE_PHY_B_LED_P1]
set_property PACKAGE_PIN B9 [get_ports GE_PHY_C_LED_P6]
set_property PACKAGE_PIN C9 [get_ports GE_PHY_C_LED_P5]
set_property PACKAGE_PIN A8 [get_ports FPGA_GE_LED_P21]
set_property PACKAGE_PIN A9 [get_ports FPGA_GE_LED_P20]

set_property PACKAGE_PIN D8 [get_ports GE_PHY_C_LED_P3]
set_property PACKAGE_PIN D9 [get_ports GE_PHY_C_LED_P4]
set_property PACKAGE_PIN F8 [get_ports GE_PHY_C_LED_P1]
set_property PACKAGE_PIN F9 [get_ports GE_PHY_C_LED_P7]
set_property PACKAGE_PIN H11 [get_ports FPGA_GE_LED_P10]
set_property PACKAGE_PIN H12 [get_ports FPGA_GE_LED_P00]
set_property PACKAGE_PIN G14 [get_ports GE_PHY_A_LED_P3]
set_property PACKAGE_PIN H14 [get_ports GE_PHY_A_LED_P5]
set_property PACKAGE_PIN J10 [get_ports GE_PHY_A_LED_P0]
set_property PACKAGE_PIN J11 [get_ports GE_PHY_A_LED_P6]
set_property PACKAGE_PIN H13 [get_ports GE_PHY_A_LED_P4]
set_property PACKAGE_PIN J13 [get_ports GE_PHY_A_LED_P7]
set_property PACKAGE_PIN G9 [get_ports GE_PHY_A_LED_P1]
set_property PACKAGE_PIN G10 [get_ports GE_PHY_B_LED_P0]
set_property PACKAGE_PIN H8 [get_ports GE_PHY_C_LED_P0]
set_property PACKAGE_PIN H9 [get_ports GE_PHY_C_LED_P2]

set_property IOSTANDARD LVCMOS33 [get_ports CPU_ENET1_LED_LNKACT]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_ENET1_LED_SPEED]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_ENET2_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_ENET2_TX_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_ESPI1_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports CPU_ESPI2_RDY]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P00]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P01]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P02]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P03]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P04]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P05]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P06]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P07]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P08]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P09]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P10]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P11]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P12]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P13]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P14]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P15]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P16]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P17]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P18]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P19]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P20]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P21]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P22]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_GE_LED_P23]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SYS_ETH_LED0]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SYS_ETH_LED1]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P0]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P1]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P2]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P3]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P4]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P5]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P6]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_LED_P7]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_A_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P0]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P1]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P2]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P3]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P4]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P5]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P6]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_LED_P7]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_B_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports FE_PHY_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P0]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P1]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P2]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P3]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P4]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P5]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P6]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_LED_P7]
set_property IOSTANDARD LVCMOS33 [get_ports GE_PHY_C_MDC]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED4]
set_property IOSTANDARD LVCMOS33 [get_ports LED5]
set_property IOSTANDARD LVCMOS33 [get_ports LED6]
set_property IOSTANDARD LVCMOS33 [get_ports SYS_LED]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P00]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P01]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P02]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P03]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P04]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P05]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P06]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P07]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P08]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P09]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P10]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P11]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P12]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P13]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P14]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P15]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P16]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P17]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P18]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P19]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P20]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P21]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P22]
set_property IOSTANDARD LVCMOS33 [get_ports SW_SEL_P23]


set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]

current_instance -quiet

create_clock -period 20.000 -name CPU_ENET2_TX_CLK -waveform {0.000 10.000} [get_ports CPU_ENET2_TX_CLK]
create_clock -period 8.000 -name FPGA_GTX_P0_CLK -waveform {0.000 4.000} [get_ports FPGA_GTX_P0_CLK_P]

set_false_path -from [get_clocks clk_out1_clk_wiz_0] -to [get_clocks clk_out2_clk_wiz_0]
set_false_path -from [get_clocks clk_out2_clk_wiz_0] -to [get_clocks clk_out1_clk_wiz_0]

set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_0_line_reset_1d_reg/D}]
set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_1_line_reset_1d_reg/D}]
set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_2_line_reset_1d_reg/D}]
set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_3_line_reset_1d_reg/D}]
set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_4_line_reset_1d_reg/D}]
set_false_path -from [get_pins {reset_reg/C}] -to [get_pins {qs_5_line_reset_1d_reg/D}]


